export const APP_ROUTES = {
  home: "/",
  hub: "/hub",
  login: "/login",
  register: "/register",
  resetPassword: "/reset-password",
  onboarding: "/onboarding",
  documents: "/documents",
  documentsScan: "/documents/scan",
  documentsScanComplete: "/documents/scan/complete",
  payslipHistory: "/documents/history",
  taxAssistant: "/documents/tax",
  financialHealth: "/financial-health",
  copilot: "/copilot",
  insights: "/insights",
  planning: "/planning",
  insurance: "/insurance",
  pension: "/pension",
  notifications: "/notifications",
  assistant: "/assistant",
  aiAgents: "/ai-agents",
  settings: "/settings",
  integrationsEmail: "/integrations/email",
  help: "/help",
  team: "/team",
  contact: "/contact",
  faq: "/faq",
  privacy: "/privacy",
  terms: "/terms",
  careers: "/careers",
  error400: "/400",
  error401: "/401",
  error403: "/403",
  error500: "/500",
} as const;

export type AppRoute = (typeof APP_ROUTES)[keyof typeof APP_ROUTES];

export const PRIVATE_ROUTES: AppRoute[] = [
  APP_ROUTES.hub,
  APP_ROUTES.onboarding,
  APP_ROUTES.documents,
  APP_ROUTES.payslipHistory,
  APP_ROUTES.taxAssistant,
  APP_ROUTES.financialHealth,
  APP_ROUTES.copilot,
  APP_ROUTES.insights,
  APP_ROUTES.insurance,
  APP_ROUTES.pension,
  APP_ROUTES.notifications,
  APP_ROUTES.assistant,
  APP_ROUTES.settings,
  APP_ROUTES.integrationsEmail,
  APP_ROUTES.help,
];
